require 'read_time_est'

RSpec.describe 'read_est method' do 
    it 'takes the "quick brown fox" string and outputs how many mins to read' do 
        result = read_est("the quick brown fox jumps over the lazy dog")
        expect(result).to eq 0.045
    end
    it 'takes "lorem ipsum" string and returns mins to read' do
        result = read_est("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non neque at felis volutpat ultrices quis sed lectus. Mauris nulla nibh, porttitor at tempus nec, venenatis ac lectus. Sed rhoncus dolor id elit tincidunt viverra. Fusce auctor venenatis magna, sit amet feugiat justo. Phasellus interdum blandit neque ut iaculis. Vestibulum quis odio tincidunt, aliquet dui id, mattis quam. Sed vel maximus tellus, at dictum ante. Mauris eget purus rutrum, aliquam metus sit amet, ultricies nisi. Aliquam interdum dolor libero. Fusce suscipit pellentesque metus. Fusce in lobortis odio. Quisque tempus erat ut risus malesuada malesuada. Duis pretium at eros in consequat. Donec eu feugiat arcu. Integer non metus ut tortor sagittis laoreet eu eget nisl. Mauris nec dui in est faucibus hendrerit nec et augue. Fusce eget est feugiat, vulputate eros nec, condimentum est. Morbi tincidunt eros ut nibh tempus, at egestas lacus ullamcorper. Nunc et elementum nunc. Sed semper tempor velit, id venenatis tortor sollicitudin id. Fusce malesuada dictum nibh, ut pharetra urna mattis sed. Sed bibendum ligula at libero scelerisque congue. Sed a dignissim diam. Aenean in mi ut orci semper malesuada. Aenean eget eros ut risus convallis dictum. Fusce sollicitudin feugiat sodales. Morbi imperdiet fringilla ipsum, ut elementum quam tristique eu. Pellentesque ullamcorper justo eleifend, mattis sem eget, viverra odio. Morbi elementum pretium eros, placerat semper massa gravida sit amet. Sed elementum velit justo, id vehicula risus gravida ut. Nam malesuada nulla imperdiet dignissim ultrices. Cras pretium mauris at ante congue, nec congue lacus porta. Sed porta sit amet leo vel sodales. Cras sed mattis metus. Proin vel tellus pulvinar, malesuada odio vitae, mollis mauris. Etiam nisi nisi, aliquam id sapien et, pellentesque sagittis ligula. Curabitur aliquet hendrerit ex eu gravida. Phasellus eu est ornare, volutpat turpis ut, consequat nunc. Nullam imperdiet eros fermentum justo finibus consectetur. Proin elementum dapibus vehicula. Suspendisse molestie auctor eros ut mollis. Duis eget urna elementum, pharetra lacus at, congue dui. Pellentesque porta, mi quis vestibulum egestas, neque lacus ultrices sapien, eget sollicitudin nibh purus facilisis elit. Cras eu augue tempor, malesuada elit non, sodales massa. Nunc venenatis nisl et lacus aliquam congue. Integer sit amet justo ligula. Sed auctor, elit eu varius semper, ante urna mollis ipsum, quis sodales turpis nulla vel odio. Nulla dictum lorem non eros gravida viverra. Donec at fermentum nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;") 
        expect(result).to eq 1.975

    end
end